// Code generated by protoc-gen-go.
// source: logtail.proto
// DO NOT EDIT!

/*
Package logtail is a generated protocol buffer package.

It is generated from these files:
	logtail.proto

It has these top-level messages:
	RequestFile
	Files
*/
package logtail

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestFile struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RequestFile) Reset()                    { *m = RequestFile{} }
func (m *RequestFile) String() string            { return proto.CompactTextString(m) }
func (*RequestFile) ProtoMessage()               {}
func (*RequestFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Files struct {
	Name             []string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Files) Reset()                    { *m = Files{} }
func (m *Files) String() string            { return proto.CompactTextString(m) }
func (*Files) ProtoMessage()               {}
func (*Files) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Files) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestFile)(nil), "logtail.RequestFile")
	proto.RegisterType((*Files)(nil), "logtail.Files")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LogTail service

type LogTailClient interface {
	GetFiles(ctx context.Context, in *RequestFile, opts ...grpc.CallOption) (*Files, error)
}

type logTailClient struct {
	cc *grpc.ClientConn
}

func NewLogTailClient(cc *grpc.ClientConn) LogTailClient {
	return &logTailClient{cc}
}

func (c *logTailClient) GetFiles(ctx context.Context, in *RequestFile, opts ...grpc.CallOption) (*Files, error) {
	out := new(Files)
	err := grpc.Invoke(ctx, "/logtail.LogTail/GetFiles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LogTail service

type LogTailServer interface {
	GetFiles(context.Context, *RequestFile) (*Files, error)
}

func RegisterLogTailServer(s *grpc.Server, srv LogTailServer) {
	s.RegisterService(&_LogTail_serviceDesc, srv)
}

func _LogTail_GetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogTailServer).GetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logtail.LogTail/GetFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogTailServer).GetFiles(ctx, req.(*RequestFile))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogTail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logtail.LogTail",
	HandlerType: (*LogTailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFiles",
			Handler:    _LogTail_GetFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logtail.proto",
}

func init() { proto.RegisterFile("logtail.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xc9, 0x4f, 0x2f,
	0x49, 0xcc, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x78, 0xb9,
	0xb8, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xdc, 0x32, 0x73, 0x52, 0x95, 0x44, 0xb9, 0x58,
	0x41, 0x74, 0xb1, 0x10, 0x0f, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xb3, 0x06,
	0xa7, 0x91, 0x2d, 0x17, 0xbb, 0x4f, 0x7e, 0x7a, 0x48, 0x62, 0x66, 0x8e, 0x90, 0x11, 0x17, 0x87,
	0x7b, 0x6a, 0x09, 0x44, 0x91, 0x88, 0x1e, 0xcc, 0x54, 0x24, 0x33, 0xa4, 0xf8, 0xe0, 0xa2, 0x60,
	0x55, 0x4a, 0x0c, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xfa, 0xf6, 0x08, 0x7d, 0x00, 0x00,
	0x00,
}
